# Generated by Django 4.0.4 on 2022-05-15 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('Habits', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('next_day_offset', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TasksType',
            fields=[
                ('task', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default=None, null=True)),
                ('start_task_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(default=None, null=True)),
                ('completion', models.BooleanField(default=None)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completion', models.BooleanField(default=None)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerApi.task')),
            ],
        ),
        migrations.CreateModel(
            name='LogTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerApi.task')),
            ],
        ),
        migrations.CreateModel(
            name='LogHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('Habits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerApi.habits')),
            ],
        ),
    ]
