# Generated by Django 4.0.3 on 2022-04-01 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plannerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='ID_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plannerApi.taskstype'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
