# Generated by Django 4.0.4 on 2022-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0003_remove_task_user_task_sber_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_task_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
