# Generated by Django 4.0.3 on 2022-04-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0004_alter_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='ID_Habits',
            new_name='Habits',
        ),
        migrations.RenameField(
            model_name='habits',
            old_name='ID_User',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='loghabits',
            old_name='ID_Habits',
            new_name='Habits',
        ),
        migrations.RenameField(
            model_name='logtasks',
            old_name='ID_Task',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='subtasks',
            old_name='ID_Task',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ID_Task',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ID_User',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='taskstype',
            old_name='task_id',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_task', to='plannerApi.taskstype'),
        ),
    ]
