# Generated by Django 4.0.4 on 2022-06-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0004_alter_task_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='sber_user_id',
            field=models.CharField(max_length=255),
        ),
    ]
