# Generated by Django 4.0.3 on 2022-04-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0005_rename_id_habits_habits_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghabits',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
