# Generated by Django 4.0.4 on 2022-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0007_taskstype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
