# Generated by Django 4.0.3 on 2022-04-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0002_alter_habits_id_user_alter_task_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
    ]
