# Generated by Django 4.0.3 on 2022-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApi', '0003_remove_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
